plugins {
    id 'com.android.application'
}

android {
    namespace 'com.h3.console'
    compileSdk 34

    defaultConfig {
        applicationId "com.h3.console"
        minSdk 24
        targetSdk 34
        versionCode 72
        versionName "2.01"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
dependencies {
    implementation 'androidx.browser:browser:1.8.0'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'com.github.mwiede:jsch:0.2.17'
}
